
CREATE TABLE ValueHistory
(
	type VARCHAR(10) NOT NULL,
	unit VARCHAR(10) NOT NULL,
	value DECIMAL(12,4) NOT NULL,
	value_time TIMESTAMP NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);